# QuestIntelligence (or just quill) by NoLogic (aka VoxelSquid). EARLY ALPHA.
# Report any bugs and suggest your amazing ideas here: https://discord.gg/jTSCfBGAUu

# Core settings of the plugin.
core-settings:

  # TODO: Переносим оставшееся в процедурную конфигурацию.
  # Some personality types will swear in their phrases. You may not like this, so I've added the option to disable it.
  swearing: true

  # Maximum duration of quest existence in ticks.
  # Default is 48000, which is two game days.
  quest-time-limit: 48000

  # Default is #FFFFFF.
  menu-button-text-color: "#FFFFFF"

  # The period between actions in ticks. Villagers eat food, produce items related to their profession and generate quests.
  # 1 second is 20 ticks.
  tick-period:

    # Default is 4800
    food: 4800

    # Default is 2400
    work: 2400

    # Default is 400
    quest: 200

  # The standard format of villagers' dialogs for every player on the server.
  # IMMERSIVE: the message from the villager will be received in a cOoL dIaLoGuE wInDoW.
  # CHAT: the message from the villager will be received via chat, classic.
  # BOTH: well... there's no need to explain, I hope?..
  default-dialogue-format: IMMERSIVE