# QuestIntelligence (or just quill) by NoLogic (aka VoxelSquid). EARLY ALPHA.
# Report any bugs and suggest your amazing ideas here: https://discord.gg/jTSCfBGAUu

# Core settings of the plugin.
core-settings:

  # Get your API key FOR FREE: https://aistudio.google.com/app/apikey
  # Currently, only Gemini IS supported.
  api-key: "AIzaSyCNEY3sTaCvuRn1mApl1NtfT0q9t2mwOeg"

  # Language of plugin messages, quests, villager names and phrases. (supported languages depends on AI)
  language: "ENGLISH"

  # The plugin messages will be automatically translated into the language specified above when plugin enables. But you can disable this and configure everything yourself.
  automatic-configuration-translation: true

  # Add your worlds here.
  enabled-worlds:
    - "world"

  # By default, all villagers are replaced by player models that have skins and races with their own unique attributes.
  # You can disable this feature or customize it in races.yml and skins.yml.
  humanoid-villagers: true

  # Some countries may have problems connecting to AI. Proxy helps.
  # HTTP, SOCKS
  proxy:
    type: HTTP
    host: PROXY_HOST
    port: 1337
    username: "PROXY_USERNAME"
    password: "PROXY_PASSWORD"

  message-prefix: "§7§l.q§8§l/ §6>> §7"

  # Important words in villagers' messages are highlighted in colors. You can customize this.
  text-formatting:
    base-color: "§f"
    important-color: "§6"
    emotional-color: "§e"

  dialogue-text-display:
    default-size: 0.28
    background-color:
      alpha: 185
      r: 0
      g: 0
      b: 0

  # The naming style affects the style in which the AI will name items.
  # Fantasy is the default, but you can write really anything here, from space dwarfs to names from the Warhammer or Star Wars universe. Or Star Trek, if you prefer. Live and prosper.
  naming-style: "Fantasy"

  # Some personality types will swear in their phrases. You may not like this, so I've added the option to disable it.
  swearing: true

  # Maximum duration of quest existence in ticks.
  # Default is 48000, which is two game days.
  quest-time-limit: 48000

  # Default is #FFFFFF.
  menu-button-text-color: "#FFFFFF"

  # The period between actions in ticks. Villagers eat food, produce items related to their profession and generate quests.
  # 1 second is 20 ticks.
  tick-period:

    # Default is 4800
    food: 4800

    # Default is 2400
    work: 2400

    # Default is 400
    quest: 200

  # The standard format of villagers' dialogs for every player on the server.
  # IMMERSIVE: the message from the villager will be received in a cOoL dIaLoGuE wInDoW.
  # CHAT: the message from the villager will be received via chat, classic.
  # BOTH: well... there's no need to explain, I hope?..
  default-dialogue-format: IMMERSIVE